---
name: test
on: [push, pull_request]

env:
  RULESET_CONVERTER_URL: https://github.com/bromite/filters/releases/download/78.0.3904.130/ruleset_converter
  ARTIFACT_DIR: artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Download dependencies
        shell: bash
        run: |
          # mkdir -p ${ARTIFACT_DIR}

          # curl -f -L ${RULESET_CONVERTER_URL} -o ruleset_converter || exit 1
          # curl -f -L https://gitee.com/xinggsf/Adblock-Rule/raw/master/mv.txt -o xinggsf_mv.txt  || exit 1

          # chmod u+x ruleset_converter
          # ./ruleset_converter --input_format=filter-list --output_format=unindexed-ruleset \
          #   --input_files=xinggsf_mv.txt \
          #   --output_file=${ARTIFACT_DIR}/filters.dat 2> /dev/null

          filters=(
            "https://easylist-downloads.adblockplus.org/easylist.txt"
            "https://easylist-downloads.adblockplus.org/easylistchina.txt"
            "https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt"
            "https://easylist-downloads.adblockplus.org/easyprivacy.txt"
            "https://easylist-downloads.adblockplus.org/fanboy-social.txt"
            "https://easylist-downloads.adblockplus.org/antiadblockfilters.txt"
            "https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt"
            "abp-filters-anti-cv-chinese.txt::https://raw.githubusercontent.com/abp-filters/abp-filters-anti-cv/master/chinese.txt"
            "https://cdn.adblockcdn.com/filters/adblock_custom.txt"
            "xinggsf_mv.txt::https://gitee.com/xinggsf/Adblock-Rule/raw/master/mv.txt"
          )

          exclude_rules=(
            '^||youaima.com/zz/'
          )

          for filter in "${filters[@]}"; do
            url="${filter##*::}"
            src="${filter%%::*}"
            src="${src##*/}"
            srcs+=",${src}"

            if [[ ! -f ${src} ]]; then
              curl -f -L "${url}" -o "${src}"
            fi

            for rule in "${exclude_rules[@]}"; do
              sed -i "\!${rule}!d" "${src}"
            done
          done
          srcs=${srcs:1}

          mkdir -p ${ARTIFACT_DIR}
          curl -f -L ${RULESET_CONVERTER_URL} -o ruleset_converter || exit 1
          chmod u+x ruleset_converter
          ./ruleset_converter --input_format=filter-list --output_format=unindexed-ruleset \
            --input_files="${srcs}" \
            --output_file=${ARTIFACT_DIR}/filters.dat 2> /dev/null

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_DIR }}
          path: ./${{ env.ARTIFACT_DIR }}

  release:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Initalize
        shell: bash
        run: |
          git config --global core.autocrlf input

      - uses: actions/checkout@master
      - name: Checkout
        shell: bash
        run: |
          git config --global user.name 'CI'
          git config --global user.email 'zhmars@users.noreply.github.com'
          git tag --force nightly
          git push origin --delete --force nightly
          git push origin HEAD --tags

      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: ${{ env.ARTIFACT_DIR }}

      - name: Create Release
        uses: softprops/action-gh-release@9993ae8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          body: |

            bromite filters

          draft: false
          prerelease: false
          files: |
            ./${{ env.ARTIFACT_DIR }}/filters.dat
