---
name: test
on: [push, pull_request]

env:
  RULESET_CONVERTER_URL: https://github.com/bromite/filters/releases/download/78.0.3904.130/ruleset_converter
  ARTIFACT_DIR: artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Download dependencies
        shell: bash
        run: |
          mkdir -p ${ARTIFACT_DIR}

          curl -f -L ${RULESET_CONVERTER_URL} -o ruleset_converter || exit 1
          curl -f -L https://gitee.com/xinggsf/Adblock-Rule/raw/master/mv.txt -o xinggsf_mv.txt  || exit 1

          chmod u+x ruleset_converter
          ./ruleset_converter --input_format=filter-list --output_format=unindexed-ruleset \
            --input_files=xinggsf_mv.txt \
            --output_file=${ARTIFACT_DIR}/filters.dat 2> /dev/null

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_DIR }}
          path: ./${{ env.ARTIFACT_DIR }}

  release:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Initalize
        shell: bash
        run: |
          git config --global core.autocrlf input

      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@9993ae8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          body: |
            ### Changes:

            bromite filters

          draft: false
          prerelease: false
          files: |
            ./artifacts/filters.dat
